// lib/utils/app_config.dart
// ─────────────────────────────────────────────────────────────────
// Production AppConfig — Environment-aware configuration
// Usage:
//   flutter run --dart-define=ENV=dev
//   flutter run --dart-define=ENV=staging
//   flutter run --dart-define=ENV=prod
// ─────────────────────────────────────────────────────────────────

class AppConfig {
  AppConfig._();

  // ── Environment ─────────────────────────────────────────────────
  static const _env = String.fromEnvironment('ENV', defaultValue: 'dev');

  static bool get isDev => _env == 'dev';
  static bool get isStaging => _env == 'staging';
  static bool get isProd => _env == 'prod';
  static bool get useMockData => isDev; // Only mock in dev

  // ── App Identity ─────────────────────────────────────────────────
  static const String appName = 'ElectroCare';
  static const String appVersion = '2.0.0';
  static const String appTagline = 'Electrical Products & Services';

  // ── API Base URLs ─────────────────────────────────────────────────
  static String get baseUrl {
    switch (_env) {
      case 'prod':
        return 'https://api.electrocare.in/v1';
      case 'staging':
        return 'https://staging.electrocare.in/v1';
      default:
        return 'https://dev.electrocare.in/v1';
    }
  }

  // ── Firebase Project IDs ──────────────────────────────────────────
  // These are set via firebase_options.dart (generated by FlutterFire CLI)
  // Run: flutterfire configure
  // This generates: lib/firebase_options.dart automatically

  // ── Razorpay ─────────────────────────────────────────────────────
  // Test key starts with rzp_test_, Production starts with rzp_live_
  static String get razorpayKey =>
      isProd ? 'rzp_live_YOUR_LIVE_KEY' : 'rzp_test_YOUR_TEST_KEY';

  // ── Google APIs ──────────────────────────────────────────────────
  // Get from: https://console.cloud.google.com/
  static const String googleMapsApiKey = 'YOUR_GOOGLE_MAPS_API_KEY';

  // ── Gemini AI ─────────────────────────────────────────────────────
  // Get from: https://makersuite.google.com/app/apikey
  static const String geminiApiKey = 'YOUR_GEMINI_API_KEY';

  // ── Firestore Collection Names ────────────────────────────────────
  // Centralised — change once, updates everywhere
  static const String usersCollection = 'users';
  static const String productsCollection = 'products';
  static const String bookingsCollection = 'bookings';
  static const String ordersCollection = 'orders';
  static const String reviewsCollection = 'reviews';
  static const String notificationsCollection = 'notifications';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableAi = true;
  static const bool enablePayments = true;
  static const bool enableMaps = true;
  static const bool enableAnalytics = true;

  // ── Timeouts & Limits ─────────────────────────────────────────────
  static const Duration apiTimeout = Duration(seconds: 15);
  static const int maxCartItems = 50;
  static const int maxProductImageSizeMb = 5;
  static const double platformFeePercent = 0.02; // 2% platform fee
}
